### ISSUE TITLE
Incorporate better maximum frequency increases

### ISSUE THREAD

**Issue by Erotemic** [Erotemic/progiter#2]
Currently if an iterator blazes through the first N items, but then slows to a sudden halt the existing frequency update adjustment code will wait a very long time before showing another frequency update. 

This case occurs when downloading lots of data, failing and retrying. The first N items are cached, so they are super quick, but the second it starts downloading an item again the processes slows way down. 

This should be adjusted so if there is a dramatic change in speed we adjust the frequency of updates to be much higher.

**Comment by edgarsi** [comment]
This goes both directions. If the first iterations are slow, sudden speed-up will cause a spam of output.

**Comment by edgarsi** [comment]
See #26

**Comment by Erotemic** [comment]
New version is merged and pushed to pypi. Thanks @edgarsi !
